### ISSUE TITLE
Make me a contributor

### ISSUE THREAD

**Issue by jpike88** [andreialecu/node-apn-http2#2]
Probably a good idea... if this is to be the root repo then you'll need some backup in case you get hit by a bus or something :p

**Comment by andreialecu** [comment]
Anyone is free to fork and keep using it. I don't know if this is going to be a root repo or not yet. We'll have to see.

We would need to add some tests first for it to have a chance at being a root repo, I think...

Feel free to contribute, and I'll add you as a contributor.
