### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by jpike88** [andreialecu/node-apn-http2#3]

**Comment by andreialecu** [comment]
It is on npm: https://www.npmjs.org/package/node-apn-http2

**Comment by jpike88** [comment]
Alright, FYI I have forked https://github.com/appfeel/node-pushnotifications to https://github.com/streaka/node-pushnotifications-http2, not sure if you use that but usually people looking for iOS push want an Android solution alongside it

**Comment by jpike88** [comment]
Should probably also update readme to mention it's on npm

**Comment by andreialecu** [comment]
There's a npm badge up top, and it mentions being able to install via `yarn` which does the same thing as npm and works using npm's repository.

**Comment by jpike88** [comment]
I've been writing for node.js for 3 years and I still have no idea what yarn is, I don't think that assumption is a safe one to make. Usually people use one or the another.

**Comment by andreialecu** [comment]
yarn is the same as npm, just much faster, especially for bigger projects.

npm5+ however has recently started being more up to par with yarn.
